name: .NET 10 CITest

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build-test-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run test cases
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Push code to deploy repository
        if: github.event_name == 'push'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone https://x-access-token:${{ secrets.DEPLOY_REPO_TOKEN }}@github.com/riyakatiyar33/TestCd-Deploy.git deploy-repo

          rsync -av --delete ./ deploy-repo/ \
            --exclude='.git/' \
            --exclude='deploy-repo/' \
            --exclude='.github/workflows/deploy.yml'

          rm -f deploy-repo/.github/workflows/ci-cd.yml

          cd deploy-repo

          git add -A
          git commit -m "Sync code from TestCd" || echo "No changes to commit"
          git push origin main